sources:
  - name: Wanted
    url: https://www.wanted.co.kr/wdlist
  - name: JobKorea
    url: https://www.jobkorea.co.kr/recruit/joblist?menucode=duty
  - name: Saramin
    url: https://www.saramin.co.kr/

keywords:
  include:
    - python
    - backend
    - "django"
    - "fastapi"
    - "engineer"
  exclude:
    - "senior"
    - "lead"
    - "manager"
    - "frontend"
    - "react"

scoring:
  title_hit: 10
  body_hit: 5
  exclude_penalty: -100

digest:
  min_score: 1
  max_items: 10
